telegram:
  bot_username: ${BOT_USERNAME}
  bot_token: ${BOT_TOKEN}}
  bot_path: ${BOT_PATH}

api:
  url: ${API_URL}

loader:
  url: ${LOADER_URL}
  path: ${LOADER_PATH}

spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

locale:
  tag: ru-RU